package com.master.mybatisgenerated;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class HouseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public HouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> houseUUIDCriteria;

        protected List<Criterion> userUUIDCriteria;

        protected List<Criterion> profileUUIDCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            houseUUIDCriteria = new ArrayList<Criterion>();
            userUUIDCriteria = new ArrayList<Criterion>();
            profileUUIDCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getHouseUUIDCriteria() {
            return houseUUIDCriteria;
        }

        protected void addHouseUUIDCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            houseUUIDCriteria.add(new Criterion(condition, value, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        protected void addHouseUUIDCriterion(String condition, UUID value1, UUID value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            houseUUIDCriteria.add(new Criterion(condition, value1, value2, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getUserUUIDCriteria() {
            return userUUIDCriteria;
        }

        protected void addUserUUIDCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            userUUIDCriteria.add(new Criterion(condition, value, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        protected void addUserUUIDCriterion(String condition, UUID value1, UUID value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            userUUIDCriteria.add(new Criterion(condition, value1, value2, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getProfileUUIDCriteria() {
            return profileUUIDCriteria;
        }

        protected void addProfileUUIDCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            profileUUIDCriteria.add(new Criterion(condition, value, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        protected void addProfileUUIDCriterion(String condition, UUID value1, UUID value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            profileUUIDCriteria.add(new Criterion(condition, value1, value2, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || houseUUIDCriteria.size() > 0
                || userUUIDCriteria.size() > 0
                || profileUUIDCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(houseUUIDCriteria);
                allCriteria.addAll(userUUIDCriteria);
                allCriteria.addAll(profileUUIDCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdhouseIsNull() {
            addCriterion("idHouse is null");
            return (Criteria) this;
        }

        public Criteria andIdhouseIsNotNull() {
            addCriterion("idHouse is not null");
            return (Criteria) this;
        }

        public Criteria andIdhouseEqualTo(Integer value) {
            addCriterion("idHouse =", value, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseNotEqualTo(Integer value) {
            addCriterion("idHouse <>", value, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseGreaterThan(Integer value) {
            addCriterion("idHouse >", value, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseGreaterThanOrEqualTo(Integer value) {
            addCriterion("idHouse >=", value, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseLessThan(Integer value) {
            addCriterion("idHouse <", value, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseLessThanOrEqualTo(Integer value) {
            addCriterion("idHouse <=", value, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseIn(List<Integer> values) {
            addCriterion("idHouse in", values, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseNotIn(List<Integer> values) {
            addCriterion("idHouse not in", values, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseBetween(Integer value1, Integer value2) {
            addCriterion("idHouse between", value1, value2, "idhouse");
            return (Criteria) this;
        }

        public Criteria andIdhouseNotBetween(Integer value1, Integer value2) {
            addCriterion("idHouse not between", value1, value2, "idhouse");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDIsNull() {
            addCriterion("houseUUID is null");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDIsNotNull() {
            addCriterion("houseUUID is not null");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDEqualTo(UUID value) {
            addHouseUUIDCriterion("houseUUID =", value, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDNotEqualTo(UUID value) {
            addHouseUUIDCriterion("houseUUID <>", value, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDGreaterThan(UUID value) {
            addHouseUUIDCriterion("houseUUID >", value, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDGreaterThanOrEqualTo(UUID value) {
            addHouseUUIDCriterion("houseUUID >=", value, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDLessThan(UUID value) {
            addHouseUUIDCriterion("houseUUID <", value, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDLessThanOrEqualTo(UUID value) {
            addHouseUUIDCriterion("houseUUID <=", value, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDLike(UUID value) {
            addHouseUUIDCriterion("houseUUID like", value, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDNotLike(UUID value) {
            addHouseUUIDCriterion("houseUUID not like", value, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDIn(List<UUID> values) {
            addHouseUUIDCriterion("houseUUID in", values, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDNotIn(List<UUID> values) {
            addHouseUUIDCriterion("houseUUID not in", values, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDBetween(UUID value1, UUID value2) {
            addHouseUUIDCriterion("houseUUID between", value1, value2, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andHouseUUIDNotBetween(UUID value1, UUID value2) {
            addHouseUUIDCriterion("houseUUID not between", value1, value2, "houseUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDIsNull() {
            addCriterion("userUUID is null");
            return (Criteria) this;
        }

        public Criteria andUserUUIDIsNotNull() {
            addCriterion("userUUID is not null");
            return (Criteria) this;
        }

        public Criteria andUserUUIDEqualTo(UUID value) {
            addUserUUIDCriterion("userUUID =", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDNotEqualTo(UUID value) {
            addUserUUIDCriterion("userUUID <>", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDGreaterThan(UUID value) {
            addUserUUIDCriterion("userUUID >", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDGreaterThanOrEqualTo(UUID value) {
            addUserUUIDCriterion("userUUID >=", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDLessThan(UUID value) {
            addUserUUIDCriterion("userUUID <", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDLessThanOrEqualTo(UUID value) {
            addUserUUIDCriterion("userUUID <=", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDLike(UUID value) {
            addUserUUIDCriterion("userUUID like", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDNotLike(UUID value) {
            addUserUUIDCriterion("userUUID not like", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDIn(List<UUID> values) {
            addUserUUIDCriterion("userUUID in", values, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDNotIn(List<UUID> values) {
            addUserUUIDCriterion("userUUID not in", values, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDBetween(UUID value1, UUID value2) {
            addUserUUIDCriterion("userUUID between", value1, value2, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDNotBetween(UUID value1, UUID value2) {
            addUserUUIDCriterion("userUUID not between", value1, value2, "userUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDIsNull() {
            addCriterion("profileUUID is null");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDIsNotNull() {
            addCriterion("profileUUID is not null");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDEqualTo(UUID value) {
            addProfileUUIDCriterion("profileUUID =", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDNotEqualTo(UUID value) {
            addProfileUUIDCriterion("profileUUID <>", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDGreaterThan(UUID value) {
            addProfileUUIDCriterion("profileUUID >", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDGreaterThanOrEqualTo(UUID value) {
            addProfileUUIDCriterion("profileUUID >=", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDLessThan(UUID value) {
            addProfileUUIDCriterion("profileUUID <", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDLessThanOrEqualTo(UUID value) {
            addProfileUUIDCriterion("profileUUID <=", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDLike(UUID value) {
            addProfileUUIDCriterion("profileUUID like", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDNotLike(UUID value) {
            addProfileUUIDCriterion("profileUUID not like", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDIn(List<UUID> values) {
            addProfileUUIDCriterion("profileUUID in", values, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDNotIn(List<UUID> values) {
            addProfileUUIDCriterion("profileUUID not in", values, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDBetween(UUID value1, UUID value2) {
            addProfileUUIDCriterion("profileUUID between", value1, value2, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDNotBetween(UUID value1, UUID value2) {
            addProfileUUIDCriterion("profileUUID not between", value1, value2, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andHouseNameIsNull() {
            addCriterion("houseName is null");
            return (Criteria) this;
        }

        public Criteria andHouseNameIsNotNull() {
            addCriterion("houseName is not null");
            return (Criteria) this;
        }

        public Criteria andHouseNameEqualTo(String value) {
            addCriterion("houseName =", value, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameNotEqualTo(String value) {
            addCriterion("houseName <>", value, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameGreaterThan(String value) {
            addCriterion("houseName >", value, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameGreaterThanOrEqualTo(String value) {
            addCriterion("houseName >=", value, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameLessThan(String value) {
            addCriterion("houseName <", value, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameLessThanOrEqualTo(String value) {
            addCriterion("houseName <=", value, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameLike(String value) {
            addCriterion("houseName like", value, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameNotLike(String value) {
            addCriterion("houseName not like", value, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameIn(List<String> values) {
            addCriterion("houseName in", values, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameNotIn(List<String> values) {
            addCriterion("houseName not in", values, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameBetween(String value1, String value2) {
            addCriterion("houseName between", value1, value2, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseNameNotBetween(String value1, String value2) {
            addCriterion("houseName not between", value1, value2, "houseName");
            return (Criteria) this;
        }

        public Criteria andHouseAddressIsNull() {
            addCriterion("houseAddress is null");
            return (Criteria) this;
        }

        public Criteria andHouseAddressIsNotNull() {
            addCriterion("houseAddress is not null");
            return (Criteria) this;
        }

        public Criteria andHouseAddressEqualTo(String value) {
            addCriterion("houseAddress =", value, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressNotEqualTo(String value) {
            addCriterion("houseAddress <>", value, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressGreaterThan(String value) {
            addCriterion("houseAddress >", value, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressGreaterThanOrEqualTo(String value) {
            addCriterion("houseAddress >=", value, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressLessThan(String value) {
            addCriterion("houseAddress <", value, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressLessThanOrEqualTo(String value) {
            addCriterion("houseAddress <=", value, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressLike(String value) {
            addCriterion("houseAddress like", value, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressNotLike(String value) {
            addCriterion("houseAddress not like", value, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressIn(List<String> values) {
            addCriterion("houseAddress in", values, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressNotIn(List<String> values) {
            addCriterion("houseAddress not in", values, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressBetween(String value1, String value2) {
            addCriterion("houseAddress between", value1, value2, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseAddressNotBetween(String value1, String value2) {
            addCriterion("houseAddress not between", value1, value2, "houseAddress");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNull() {
            addCriterion("houseType is null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNotNull() {
            addCriterion("houseType is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeEqualTo(String value) {
            addCriterion("houseType =", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotEqualTo(String value) {
            addCriterion("houseType <>", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThan(String value) {
            addCriterion("houseType >", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("houseType >=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThan(String value) {
            addCriterion("houseType <", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThanOrEqualTo(String value) {
            addCriterion("houseType <=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLike(String value) {
            addCriterion("houseType like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotLike(String value) {
            addCriterion("houseType not like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIn(List<String> values) {
            addCriterion("houseType in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotIn(List<String> values) {
            addCriterion("houseType not in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeBetween(String value1, String value2) {
            addCriterion("houseType between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotBetween(String value1, String value2) {
            addCriterion("houseType not between", value1, value2, "houseType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table houses
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 07 02:27:37 EEST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table houses
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}