package com.master.mybatisgenerated;

public class House {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.idHouse
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    private Integer idhouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.houseUUID
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    private String houseUUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.houseName
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    private String houseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.houseAddress
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    private String houseAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.houseType
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.Users_idUser
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.Profiles_idProfile
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    private Integer profileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.idHouse
     *
     * @return the value of houses.idHouse
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public Integer getIdhouse() {
        return idhouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.idHouse
     *
     * @param idhouse the value for houses.idHouse
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public void setIdhouse(Integer idhouse) {
        this.idhouse = idhouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.houseUUID
     *
     * @return the value of houses.houseUUID
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public String getHouseUUID() {
        return houseUUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.houseUUID
     *
     * @param houseUUID the value for houses.houseUUID
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public void setHouseUUID(String houseUUID) {
        this.houseUUID = houseUUID == null ? null : houseUUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.houseName
     *
     * @return the value of houses.houseName
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public String getHouseName() {
        return houseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.houseName
     *
     * @param houseName the value for houses.houseName
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public void setHouseName(String houseName) {
        this.houseName = houseName == null ? null : houseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.houseAddress
     *
     * @return the value of houses.houseAddress
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public String getHouseAddress() {
        return houseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.houseAddress
     *
     * @param houseAddress the value for houses.houseAddress
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public void setHouseAddress(String houseAddress) {
        this.houseAddress = houseAddress == null ? null : houseAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.houseType
     *
     * @return the value of houses.houseType
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.houseType
     *
     * @param houseType the value for houses.houseType
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.Users_idUser
     *
     * @return the value of houses.Users_idUser
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.Users_idUser
     *
     * @param userId the value for houses.Users_idUser
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.Profiles_idProfile
     *
     * @return the value of houses.Profiles_idProfile
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.Profiles_idProfile
     *
     * @param profileId the value for houses.Profiles_idProfile
     *
     * @mbggenerated Sun Sep 23 12:55:53 EEST 2012
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
}