package com.master.mybatisgenerated;

import com.master.mybatisgenerated.House;
import com.master.mybatisgenerated.HouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int countByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int deleteByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int deleteByPrimaryKey(Integer idhouse);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    List<House> selectByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    House selectByPrimaryKey(Integer idhouse);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int updateByExampleSelective(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int updateByExample(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houses
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int updateByPrimaryKey(House record);
}