package com.master.mybatisgenerated;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class ProfileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public ProfileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> profileUUIDCriteria;

        protected List<Criterion> userUUIDCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            profileUUIDCriteria = new ArrayList<Criterion>();
            userUUIDCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getProfileUUIDCriteria() {
            return profileUUIDCriteria;
        }

        protected void addProfileUUIDCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            profileUUIDCriteria.add(new Criterion(condition, value, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        protected void addProfileUUIDCriterion(String condition, UUID value1, UUID value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            profileUUIDCriteria.add(new Criterion(condition, value1, value2, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getUserUUIDCriteria() {
            return userUUIDCriteria;
        }

        protected void addUserUUIDCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            userUUIDCriteria.add(new Criterion(condition, value, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        protected void addUserUUIDCriterion(String condition, UUID value1, UUID value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            userUUIDCriteria.add(new Criterion(condition, value1, value2, "com.master.mybatis.typehandler.UuidTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || profileUUIDCriteria.size() > 0
                || userUUIDCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(profileUUIDCriteria);
                allCriteria.addAll(userUUIDCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdprofileIsNull() {
            addCriterion("idProfile is null");
            return (Criteria) this;
        }

        public Criteria andIdprofileIsNotNull() {
            addCriterion("idProfile is not null");
            return (Criteria) this;
        }

        public Criteria andIdprofileEqualTo(Integer value) {
            addCriterion("idProfile =", value, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileNotEqualTo(Integer value) {
            addCriterion("idProfile <>", value, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileGreaterThan(Integer value) {
            addCriterion("idProfile >", value, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileGreaterThanOrEqualTo(Integer value) {
            addCriterion("idProfile >=", value, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileLessThan(Integer value) {
            addCriterion("idProfile <", value, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileLessThanOrEqualTo(Integer value) {
            addCriterion("idProfile <=", value, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileIn(List<Integer> values) {
            addCriterion("idProfile in", values, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileNotIn(List<Integer> values) {
            addCriterion("idProfile not in", values, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileBetween(Integer value1, Integer value2) {
            addCriterion("idProfile between", value1, value2, "idprofile");
            return (Criteria) this;
        }

        public Criteria andIdprofileNotBetween(Integer value1, Integer value2) {
            addCriterion("idProfile not between", value1, value2, "idprofile");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDIsNull() {
            addCriterion("profileUUID is null");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDIsNotNull() {
            addCriterion("profileUUID is not null");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDEqualTo(UUID value) {
            addProfileUUIDCriterion("profileUUID =", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDNotEqualTo(UUID value) {
            addProfileUUIDCriterion("profileUUID <>", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDGreaterThan(UUID value) {
            addProfileUUIDCriterion("profileUUID >", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDGreaterThanOrEqualTo(UUID value) {
            addProfileUUIDCriterion("profileUUID >=", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDLessThan(UUID value) {
            addProfileUUIDCriterion("profileUUID <", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDLessThanOrEqualTo(UUID value) {
            addProfileUUIDCriterion("profileUUID <=", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDLike(UUID value) {
            addProfileUUIDCriterion("profileUUID like", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDNotLike(UUID value) {
            addProfileUUIDCriterion("profileUUID not like", value, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDIn(List<UUID> values) {
            addProfileUUIDCriterion("profileUUID in", values, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDNotIn(List<UUID> values) {
            addProfileUUIDCriterion("profileUUID not in", values, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDBetween(UUID value1, UUID value2) {
            addProfileUUIDCriterion("profileUUID between", value1, value2, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andProfileUUIDNotBetween(UUID value1, UUID value2) {
            addProfileUUIDCriterion("profileUUID not between", value1, value2, "profileUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDIsNull() {
            addCriterion("userUUID is null");
            return (Criteria) this;
        }

        public Criteria andUserUUIDIsNotNull() {
            addCriterion("userUUID is not null");
            return (Criteria) this;
        }

        public Criteria andUserUUIDEqualTo(UUID value) {
            addUserUUIDCriterion("userUUID =", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDNotEqualTo(UUID value) {
            addUserUUIDCriterion("userUUID <>", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDGreaterThan(UUID value) {
            addUserUUIDCriterion("userUUID >", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDGreaterThanOrEqualTo(UUID value) {
            addUserUUIDCriterion("userUUID >=", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDLessThan(UUID value) {
            addUserUUIDCriterion("userUUID <", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDLessThanOrEqualTo(UUID value) {
            addUserUUIDCriterion("userUUID <=", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDLike(UUID value) {
            addUserUUIDCriterion("userUUID like", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDNotLike(UUID value) {
            addUserUUIDCriterion("userUUID not like", value, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDIn(List<UUID> values) {
            addUserUUIDCriterion("userUUID in", values, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDNotIn(List<UUID> values) {
            addUserUUIDCriterion("userUUID not in", values, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDBetween(UUID value1, UUID value2) {
            addUserUUIDCriterion("userUUID between", value1, value2, "userUUID");
            return (Criteria) this;
        }

        public Criteria andUserUUIDNotBetween(UUID value1, UUID value2) {
            addUserUUIDCriterion("userUUID not between", value1, value2, "userUUID");
            return (Criteria) this;
        }

        public Criteria andProfileNameIsNull() {
            addCriterion("profileName is null");
            return (Criteria) this;
        }

        public Criteria andProfileNameIsNotNull() {
            addCriterion("profileName is not null");
            return (Criteria) this;
        }

        public Criteria andProfileNameEqualTo(String value) {
            addCriterion("profileName =", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameNotEqualTo(String value) {
            addCriterion("profileName <>", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameGreaterThan(String value) {
            addCriterion("profileName >", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameGreaterThanOrEqualTo(String value) {
            addCriterion("profileName >=", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameLessThan(String value) {
            addCriterion("profileName <", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameLessThanOrEqualTo(String value) {
            addCriterion("profileName <=", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameLike(String value) {
            addCriterion("profileName like", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameNotLike(String value) {
            addCriterion("profileName not like", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameIn(List<String> values) {
            addCriterion("profileName in", values, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameNotIn(List<String> values) {
            addCriterion("profileName not in", values, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameBetween(String value1, String value2) {
            addCriterion("profileName between", value1, value2, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameNotBetween(String value1, String value2) {
            addCriterion("profileName not between", value1, value2, "profileName");
            return (Criteria) this;
        }

        public Criteria andElectricityRateIsNull() {
            addCriterion("electricityRate is null");
            return (Criteria) this;
        }

        public Criteria andElectricityRateIsNotNull() {
            addCriterion("electricityRate is not null");
            return (Criteria) this;
        }

        public Criteria andElectricityRateEqualTo(Integer value) {
            addCriterion("electricityRate =", value, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateNotEqualTo(Integer value) {
            addCriterion("electricityRate <>", value, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateGreaterThan(Integer value) {
            addCriterion("electricityRate >", value, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("electricityRate >=", value, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateLessThan(Integer value) {
            addCriterion("electricityRate <", value, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateLessThanOrEqualTo(Integer value) {
            addCriterion("electricityRate <=", value, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateIn(List<Integer> values) {
            addCriterion("electricityRate in", values, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateNotIn(List<Integer> values) {
            addCriterion("electricityRate not in", values, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateBetween(Integer value1, Integer value2) {
            addCriterion("electricityRate between", value1, value2, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andElectricityRateNotBetween(Integer value1, Integer value2) {
            addCriterion("electricityRate not between", value1, value2, "electricityRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateIsNull() {
            addCriterion("waterRate is null");
            return (Criteria) this;
        }

        public Criteria andWaterRateIsNotNull() {
            addCriterion("waterRate is not null");
            return (Criteria) this;
        }

        public Criteria andWaterRateEqualTo(Integer value) {
            addCriterion("waterRate =", value, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateNotEqualTo(Integer value) {
            addCriterion("waterRate <>", value, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateGreaterThan(Integer value) {
            addCriterion("waterRate >", value, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("waterRate >=", value, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateLessThan(Integer value) {
            addCriterion("waterRate <", value, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateLessThanOrEqualTo(Integer value) {
            addCriterion("waterRate <=", value, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateIn(List<Integer> values) {
            addCriterion("waterRate in", values, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateNotIn(List<Integer> values) {
            addCriterion("waterRate not in", values, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateBetween(Integer value1, Integer value2) {
            addCriterion("waterRate between", value1, value2, "waterRate");
            return (Criteria) this;
        }

        public Criteria andWaterRateNotBetween(Integer value1, Integer value2) {
            addCriterion("waterRate not between", value1, value2, "waterRate");
            return (Criteria) this;
        }

        public Criteria andGasRateIsNull() {
            addCriterion("gasRate is null");
            return (Criteria) this;
        }

        public Criteria andGasRateIsNotNull() {
            addCriterion("gasRate is not null");
            return (Criteria) this;
        }

        public Criteria andGasRateEqualTo(Integer value) {
            addCriterion("gasRate =", value, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateNotEqualTo(Integer value) {
            addCriterion("gasRate <>", value, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateGreaterThan(Integer value) {
            addCriterion("gasRate >", value, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("gasRate >=", value, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateLessThan(Integer value) {
            addCriterion("gasRate <", value, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateLessThanOrEqualTo(Integer value) {
            addCriterion("gasRate <=", value, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateIn(List<Integer> values) {
            addCriterion("gasRate in", values, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateNotIn(List<Integer> values) {
            addCriterion("gasRate not in", values, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateBetween(Integer value1, Integer value2) {
            addCriterion("gasRate between", value1, value2, "gasRate");
            return (Criteria) this;
        }

        public Criteria andGasRateNotBetween(Integer value1, Integer value2) {
            addCriterion("gasRate not between", value1, value2, "gasRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateIsNull() {
            addCriterion("lightsRate is null");
            return (Criteria) this;
        }

        public Criteria andLightsRateIsNotNull() {
            addCriterion("lightsRate is not null");
            return (Criteria) this;
        }

        public Criteria andLightsRateEqualTo(Integer value) {
            addCriterion("lightsRate =", value, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateNotEqualTo(Integer value) {
            addCriterion("lightsRate <>", value, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateGreaterThan(Integer value) {
            addCriterion("lightsRate >", value, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("lightsRate >=", value, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateLessThan(Integer value) {
            addCriterion("lightsRate <", value, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateLessThanOrEqualTo(Integer value) {
            addCriterion("lightsRate <=", value, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateIn(List<Integer> values) {
            addCriterion("lightsRate in", values, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateNotIn(List<Integer> values) {
            addCriterion("lightsRate not in", values, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateBetween(Integer value1, Integer value2) {
            addCriterion("lightsRate between", value1, value2, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andLightsRateNotBetween(Integer value1, Integer value2) {
            addCriterion("lightsRate not between", value1, value2, "lightsRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateIsNull() {
            addCriterion("temperatureRate is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateIsNotNull() {
            addCriterion("temperatureRate is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateEqualTo(Integer value) {
            addCriterion("temperatureRate =", value, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateNotEqualTo(Integer value) {
            addCriterion("temperatureRate <>", value, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateGreaterThan(Integer value) {
            addCriterion("temperatureRate >", value, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("temperatureRate >=", value, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateLessThan(Integer value) {
            addCriterion("temperatureRate <", value, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateLessThanOrEqualTo(Integer value) {
            addCriterion("temperatureRate <=", value, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateIn(List<Integer> values) {
            addCriterion("temperatureRate in", values, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateNotIn(List<Integer> values) {
            addCriterion("temperatureRate not in", values, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateBetween(Integer value1, Integer value2) {
            addCriterion("temperatureRate between", value1, value2, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andTemperatureRateNotBetween(Integer value1, Integer value2) {
            addCriterion("temperatureRate not between", value1, value2, "temperatureRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateIsNull() {
            addCriterion("fireProtectionRate is null");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateIsNotNull() {
            addCriterion("fireProtectionRate is not null");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateEqualTo(Integer value) {
            addCriterion("fireProtectionRate =", value, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateNotEqualTo(Integer value) {
            addCriterion("fireProtectionRate <>", value, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateGreaterThan(Integer value) {
            addCriterion("fireProtectionRate >", value, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("fireProtectionRate >=", value, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateLessThan(Integer value) {
            addCriterion("fireProtectionRate <", value, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateLessThanOrEqualTo(Integer value) {
            addCriterion("fireProtectionRate <=", value, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateIn(List<Integer> values) {
            addCriterion("fireProtectionRate in", values, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateNotIn(List<Integer> values) {
            addCriterion("fireProtectionRate not in", values, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateBetween(Integer value1, Integer value2) {
            addCriterion("fireProtectionRate between", value1, value2, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andFireProtectionRateNotBetween(Integer value1, Integer value2) {
            addCriterion("fireProtectionRate not between", value1, value2, "fireProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateIsNull() {
            addCriterion("stealProtectionRate is null");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateIsNotNull() {
            addCriterion("stealProtectionRate is not null");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateEqualTo(Integer value) {
            addCriterion("stealProtectionRate =", value, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateNotEqualTo(Integer value) {
            addCriterion("stealProtectionRate <>", value, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateGreaterThan(Integer value) {
            addCriterion("stealProtectionRate >", value, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("stealProtectionRate >=", value, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateLessThan(Integer value) {
            addCriterion("stealProtectionRate <", value, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateLessThanOrEqualTo(Integer value) {
            addCriterion("stealProtectionRate <=", value, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateIn(List<Integer> values) {
            addCriterion("stealProtectionRate in", values, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateNotIn(List<Integer> values) {
            addCriterion("stealProtectionRate not in", values, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateBetween(Integer value1, Integer value2) {
            addCriterion("stealProtectionRate between", value1, value2, "stealProtectionRate");
            return (Criteria) this;
        }

        public Criteria andStealProtectionRateNotBetween(Integer value1, Integer value2) {
            addCriterion("stealProtectionRate not between", value1, value2, "stealProtectionRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table profiles
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 07 00:57:29 EEST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table profiles
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}