package com.master.mybatisgenerated;

import java.util.UUID;

public class Profile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.idProfile
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private Integer idprofile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.profileUUID
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private UUID profileUUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.userUUID
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private UUID userUUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.profileName
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private String profileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.electricityRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private Integer electricityRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.waterRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private Integer waterRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.gasRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private Integer gasRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.lightsRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private Integer lightsRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.temperatureRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private Integer temperatureRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.fireProtectionRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private Integer fireProtectionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profiles.stealProtectionRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    private Integer stealProtectionRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.idProfile
     *
     * @return the value of profiles.idProfile
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Integer getIdprofile() {
        return idprofile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.idProfile
     *
     * @param idprofile the value for profiles.idProfile
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setIdprofile(Integer idprofile) {
        this.idprofile = idprofile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.profileUUID
     *
     * @return the value of profiles.profileUUID
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public UUID getProfileUUID() {
        return profileUUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.profileUUID
     *
     * @param profileUUID the value for profiles.profileUUID
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setProfileUUID(UUID profileUUID) {
        this.profileUUID = profileUUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.userUUID
     *
     * @return the value of profiles.userUUID
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public UUID getUserUUID() {
        return userUUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.userUUID
     *
     * @param userUUID the value for profiles.userUUID
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setUserUUID(UUID userUUID) {
        this.userUUID = userUUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.profileName
     *
     * @return the value of profiles.profileName
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.profileName
     *
     * @param profileName the value for profiles.profileName
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName == null ? null : profileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.electricityRate
     *
     * @return the value of profiles.electricityRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Integer getElectricityRate() {
        return electricityRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.electricityRate
     *
     * @param electricityRate the value for profiles.electricityRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setElectricityRate(Integer electricityRate) {
        this.electricityRate = electricityRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.waterRate
     *
     * @return the value of profiles.waterRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Integer getWaterRate() {
        return waterRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.waterRate
     *
     * @param waterRate the value for profiles.waterRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setWaterRate(Integer waterRate) {
        this.waterRate = waterRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.gasRate
     *
     * @return the value of profiles.gasRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Integer getGasRate() {
        return gasRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.gasRate
     *
     * @param gasRate the value for profiles.gasRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setGasRate(Integer gasRate) {
        this.gasRate = gasRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.lightsRate
     *
     * @return the value of profiles.lightsRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Integer getLightsRate() {
        return lightsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.lightsRate
     *
     * @param lightsRate the value for profiles.lightsRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setLightsRate(Integer lightsRate) {
        this.lightsRate = lightsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.temperatureRate
     *
     * @return the value of profiles.temperatureRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Integer getTemperatureRate() {
        return temperatureRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.temperatureRate
     *
     * @param temperatureRate the value for profiles.temperatureRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setTemperatureRate(Integer temperatureRate) {
        this.temperatureRate = temperatureRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.fireProtectionRate
     *
     * @return the value of profiles.fireProtectionRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Integer getFireProtectionRate() {
        return fireProtectionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.fireProtectionRate
     *
     * @param fireProtectionRate the value for profiles.fireProtectionRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setFireProtectionRate(Integer fireProtectionRate) {
        this.fireProtectionRate = fireProtectionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profiles.stealProtectionRate
     *
     * @return the value of profiles.stealProtectionRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public Integer getStealProtectionRate() {
        return stealProtectionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profiles.stealProtectionRate
     *
     * @param stealProtectionRate the value for profiles.stealProtectionRate
     *
     * @mbggenerated Sun Oct 07 00:57:29 EEST 2012
     */
    public void setStealProtectionRate(Integer stealProtectionRate) {
        this.stealProtectionRate = stealProtectionRate;
    }
}