package com.master.mybatisgenerated;

import com.master.mybatisgenerated.UserCredentials;
import com.master.mybatisgenerated.UserCredentialsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCredentialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int countByExample(UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int deleteByExample(UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int deleteByPrimaryKey(Integer idcredential);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int insert(UserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int insertSelective(UserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    List<UserCredentials> selectByExample(UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    UserCredentials selectByPrimaryKey(Integer idcredential);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int updateByExampleSelective(@Param("record") UserCredentials record, @Param("example") UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int updateByExample(@Param("record") UserCredentials record, @Param("example") UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int updateByPrimaryKeySelective(UserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Mon Oct 01 23:49:32 EEST 2012
     */
    int updateByPrimaryKey(UserCredentials record);
}