package com.master.mybatisgenerated;

import com.master.mybatisgenerated.UserCredentials;
import com.master.mybatisgenerated.UserCredentialsExample;
import java.util.List;
import java.util.UUID;

import org.apache.ibatis.annotations.Param;

public interface UserCredentialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int countByExample(UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int deleteByExample(UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int deleteByPrimaryKey(Integer idcredential);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int insert(UserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int insertSelective(UserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    List<UserCredentials> selectByExample(UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    UserCredentials selectByPrimaryKey(Integer idcredential);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int updateByExampleSelective(@Param("record") UserCredentials record, @Param("example") UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int updateByExample(@Param("record") UserCredentials record, @Param("example") UserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int updateByPrimaryKeySelective(UserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercredentials
     *
     * @mbggenerated Sun Oct 07 02:27:37 EEST 2012
     */
    int updateByPrimaryKey(UserCredentials record);

    /**
     * Queue db to get credentials by user uuid
     *
     * @param uuid
     * @return UserCredentials
     */
    UserCredentials selectByUuid(UUID uuid);
}