package com.master.mybatis.dao;

import com.master.common.type.UserRole;
import com.master.mybatis.model.Authorities;
import com.master.mybatis.model.AuthoritiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @SelectProvider(type=AuthoritiesSqlProvider.class, method="countByExample")
    int countByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @DeleteProvider(type=AuthoritiesSqlProvider.class, method="deleteByExample")
    int deleteByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @Insert({
        "insert into authorities (username, authority)",
        "values (#{username,jdbcType=VARCHAR}, #{authority,jdbcType=VARCHAR})"
    })
    int insert(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @InsertProvider(type=AuthoritiesSqlProvider.class, method="insertSelective")
    int insertSelective(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @SelectProvider(type=AuthoritiesSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="username", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="authority", javaType=UserRole.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Authorities> selectByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @UpdateProvider(type=AuthoritiesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @UpdateProvider(type=AuthoritiesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);
}