package com.master.mybatis.dao;

import com.master.mybatis.model.Rates;
import com.master.mybatis.model.RatesExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @SelectProvider(type=RatesSqlProvider.class, method="countByExample")
    int countByExample(RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @DeleteProvider(type=RatesSqlProvider.class, method="deleteByExample")
    int deleteByExample(RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @Insert({
        "insert into rates (username, datetime, ",
        "sensor1, sensor2, sensor3, ",
        "sensor4, sensor5)",
        "values (#{username,jdbcType=VARCHAR}, #{dateTime,jdbcType=TIMESTAMP}, ",
        "#{sensor1,jdbcType=REAL}, #{sensor2,jdbcType=REAL}, #{sensor3,jdbcType=REAL}, ",
        "#{sensor4,jdbcType=REAL}, #{sensor5,jdbcType=REAL})"
    })
    int insert(Rates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @InsertProvider(type=RatesSqlProvider.class, method="insertSelective")
    int insertSelective(Rates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @SelectProvider(type=RatesSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="username", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="datetime", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="sensor1", javaType=Float.class, jdbcType=JdbcType.REAL),
        @Arg(column="sensor2", javaType=Float.class, jdbcType=JdbcType.REAL),
        @Arg(column="sensor3", javaType=Float.class, jdbcType=JdbcType.REAL),
        @Arg(column="sensor4", javaType=Float.class, jdbcType=JdbcType.REAL),
        @Arg(column="sensor5", javaType=Float.class, jdbcType=JdbcType.REAL)
    })
    List<Rates> selectByExample(RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @UpdateProvider(type=RatesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Rates record, @Param("example") RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    @UpdateProvider(type=RatesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Rates record, @Param("example") RatesExample example);
}