package com.master.mybatis.dao;

import com.master.mybatis.model.Users;
import com.master.mybatis.model.UsersExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @SelectProvider(type=UsersSqlProvider.class, method="countByExample")
    int countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @DeleteProvider(type=UsersSqlProvider.class, method="deleteByExample")
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @Delete({
        "delete from users",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @Insert({
        "insert into users (username, password, ",
        "first_name, last_name, ",
        "enabled, date_created)",
        "values (#{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{firstName,jdbcType=VARCHAR}, #{lastName,jdbcType=VARCHAR}, ",
        "#{enabled,jdbcType=TINYINT}, #{dateCreated,jdbcType=DATE})"
    })
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @InsertProvider(type=UsersSqlProvider.class, method="insertSelective")
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @SelectProvider(type=UsersSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="username", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="first_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="last_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="enabled", javaType=Boolean.class, jdbcType=JdbcType.TINYINT),
        @Arg(column="date_created", javaType=Date.class, jdbcType=JdbcType.DATE)
    })
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @Select({
        "select",
        "username, password, first_name, last_name, enabled, date_created",
        "from users",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="username", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="first_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="last_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="enabled", javaType=Boolean.class, jdbcType=JdbcType.TINYINT),
        @Arg(column="date_created", javaType=Date.class, jdbcType=JdbcType.DATE)
    })
    Users selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jan 31 22:25:01 EET 2013
     */
    @Update({
        "update users",
        "set password = #{password,jdbcType=VARCHAR},",
          "first_name = #{firstName,jdbcType=VARCHAR},",
          "last_name = #{lastName,jdbcType=VARCHAR},",
          "enabled = #{enabled,jdbcType=TINYINT},",
          "date_created = #{dateCreated,jdbcType=DATE}",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Users record);
}