package com.master.mybatis.model;

import java.util.Date;

public class Rates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rates.username
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rates.datetime
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    private Date dateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rates.sensor1
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    private Float sensor1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rates.sensor2
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    private Float sensor2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rates.sensor3
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    private Float sensor3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rates.sensor4
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    private Float sensor4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rates.sensor5
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    private Float sensor5;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public Rates(String username, Date dateTime, Float sensor1, Float sensor2, Float sensor3, Float sensor4, Float sensor5) {
        this.username = username;
        this.dateTime = dateTime;
        this.sensor1 = sensor1;
        this.sensor2 = sensor2;
        this.sensor3 = sensor3;
        this.sensor4 = sensor4;
        this.sensor5 = sensor5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rates
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public Rates() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rates.username
     *
     * @return the value of rates.username
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rates.username
     *
     * @param username the value for rates.username
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rates.datetime
     *
     * @return the value of rates.datetime
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rates.datetime
     *
     * @param dateTime the value for rates.datetime
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rates.sensor1
     *
     * @return the value of rates.sensor1
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public Float getSensor1() {
        return sensor1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rates.sensor1
     *
     * @param sensor1 the value for rates.sensor1
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public void setSensor1(Float sensor1) {
        this.sensor1 = sensor1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rates.sensor2
     *
     * @return the value of rates.sensor2
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public Float getSensor2() {
        return sensor2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rates.sensor2
     *
     * @param sensor2 the value for rates.sensor2
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public void setSensor2(Float sensor2) {
        this.sensor2 = sensor2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rates.sensor3
     *
     * @return the value of rates.sensor3
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public Float getSensor3() {
        return sensor3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rates.sensor3
     *
     * @param sensor3 the value for rates.sensor3
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public void setSensor3(Float sensor3) {
        this.sensor3 = sensor3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rates.sensor4
     *
     * @return the value of rates.sensor4
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public Float getSensor4() {
        return sensor4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rates.sensor4
     *
     * @param sensor4 the value for rates.sensor4
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public void setSensor4(Float sensor4) {
        this.sensor4 = sensor4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rates.sensor5
     *
     * @return the value of rates.sensor5
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public Float getSensor5() {
        return sensor5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rates.sensor5
     *
     * @param sensor5 the value for rates.sensor5
     *
     * @mbggenerated Thu Jan 31 22:25:02 EET 2013
     */
    public void setSensor5(Float sensor5) {
        this.sensor5 = sensor5;
    }
}